import Head from 'next/head';
import Image from 'next/image';
import Script from 'next/script';

import Map from '../components/Map';

//import styles from '../styles/Home.module.css';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Spreeberlin</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />

                <link
                    href='https://api.mapbox.com/mapbox-gl-js/v2.5.1/mapbox-gl.css'
                    rel='stylesheet'
                />
            </Head>

            
        </div>
    );
}
