import Head from 'next/head';
import Image from 'next/image';

//import styles from '../styles/Home.module.css';


export default function Visionen() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main>
                
                    <div className='content'>
                        <h1>Visionen</h1>
                    </div>
              
            </main>
        </div>
    );
}
